### ISSUE TITLE
Correct Text Problems

### ISSUE THREAD

**Issue by aht360** [aht360/gustavo-albuquerque-website#52]
Some texts have erros because of accents. Correct it.

**Comment by aht360** [comment]
I think this is a heroku especific problem, running the website locally i didn't have this bug. 
![image](https://user-images.githubusercontent.com/21069834/80498992-cd187380-8942-11ea-94f6-d1446ef29f14.png)

**Comment by acmh** [comment]
I know, but we need to solve it on heroku. Please search more about it Thanks!

**Comment by acmh** [comment]
Try this:
`<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>` 
in the head section

**Comment by aht360** [comment]
Got it! The code worked!
https://tableless.com.br/html-encode-utf-8/
